trigger: none

parameters:
  - name: modulesToPublish
    displayName: Modules To Publish
    type: object
    default:
      - name: resource-group
        version: 0.1

variables:
  containerRegistry: acrmarcelmichau
  modulePath: bicep/modules

stages:
  - stage: Publish
    jobs:
      - job: Publish
        pool:
          vmImage: ubuntu-latest

        steps:
          - ${{ each module in parameters.modulesToPublish }}:
              - task: AzureCLI@1
                inputs:
                  azureSubscription: PersonalSubscriptionServiceConnection
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    az version
                    az bicep version
                    az bicep publish --file modules/${{module.name}}/main.bicep --target br:$(containerRegistry).azurecr.io/$(modulePath)/${{module.name}}:v${{module.version}}
                displayName: 'Publish Bicep Module - ${{module.name}}'
